// source: common/common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.kakaopaysec.GrpcApproval', null, global);
goog.exportSymbol('proto.kakaopaysec.GrpcCommonHeader', null, global);
goog.exportSymbol('proto.kakaopaysec.GrpcCommonHeader.ThSysTcd', null, global);
goog.exportSymbol('proto.kakaopaysec.GrpcCommonHeader.ThTrTcd', null, global);
goog.exportSymbol('proto.kakaopaysec.GrpcFep', null, global);
goog.exportSymbol('proto.kakaopaysec.GrpcMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kakaopaysec.GrpcCommonHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kakaopaysec.GrpcCommonHeader.repeatedFields_, null);
};
goog.inherits(proto.kakaopaysec.GrpcCommonHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kakaopaysec.GrpcCommonHeader.displayName = 'proto.kakaopaysec.GrpcCommonHeader';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kakaopaysec.GrpcApproval = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kakaopaysec.GrpcApproval, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kakaopaysec.GrpcApproval.displayName = 'proto.kakaopaysec.GrpcApproval';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kakaopaysec.GrpcMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kakaopaysec.GrpcMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kakaopaysec.GrpcMessage.displayName = 'proto.kakaopaysec.GrpcMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kakaopaysec.GrpcFep = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kakaopaysec.GrpcFep, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kakaopaysec.GrpcFep.displayName = 'proto.kakaopaysec.GrpcFep';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kakaopaysec.GrpcCommonHeader.repeatedFields_ = [30];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.kakaopaysec.GrpcCommonHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kakaopaysec.GrpcCommonHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcCommonHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    thTrTcd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    thIfTcd: jspb.Message.getFieldWithDefault(msg, 2, ""),
    thSrcIfTcd: jspb.Message.getFieldWithDefault(msg, 3, ""),
    mgrApvC: jspb.Message.getFieldWithDefault(msg, 4, ""),
    guid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    thTrId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    thScrNo: jspb.Message.getFieldWithDefault(msg, 7, ""),
    thTrRespTcd: jspb.Message.getFieldWithDefault(msg, 8, ""),
    thContTrTcd: jspb.Message.getFieldWithDefault(msg, 9, ""),
    thQryC: jspb.Message.getFieldWithDefault(msg, 10, ""),
    thDumTrTcd: jspb.Message.getFieldWithDefault(msg, 11, ""),
    thTrDt: jspb.Message.getFieldWithDefault(msg, 12, ""),
    thTrDlTmd: jspb.Message.getFieldWithDefault(msg, 13, ""),
    thSysTcd: jspb.Message.getFieldWithDefault(msg, 14, 0),
    thTrCcd: jspb.Message.getFieldWithDefault(msg, 15, ""),
    thBizDt: jspb.Message.getFieldWithDefault(msg, 16, ""),
    thBtnAuthTcd: jspb.Message.getFieldWithDefault(msg, 17, ""),
    mdaTcd: jspb.Message.getFieldWithDefault(msg, 18, ""),
    onlnUserId: jspb.Message.getFieldWithDefault(msg, 19, ""),
    blngDeptCod: jspb.Message.getFieldWithDefault(msg, 20, ""),
    thPwdErNcIncYn: jspb.Message.getFieldWithDefault(msg, 21, ""),
    thAcPwdCfmtTcd: jspb.Message.getFieldWithDefault(msg, 22, ""),
    userGrpAuthTcd: jspb.Message.getFieldWithDefault(msg, 23, ""),
    wrkTmnlId: jspb.Message.getFieldWithDefault(msg, 24, ""),
    thConnLocTcd: jspb.Message.getFieldWithDefault(msg, 25, ""),
    thMacAdr: jspb.Message.getFieldWithDefault(msg, 26, ""),
    thIpTcd: jspb.Message.getFieldWithDefault(msg, 27, ""),
    thConnPbipAdr: jspb.Message.getFieldWithDefault(msg, 28, ""),
    thConnPripAdr: jspb.Message.getFieldWithDefault(msg, 29, ""),
    contTrkeyList: (f = jspb.Message.getRepeatedField(msg, 30)) == null ? undefined : f,
    fdsMoblDvcIdfy: jspb.Message.getFieldWithDefault(msg, 31, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kakaopaysec.GrpcCommonHeader}
 */
proto.kakaopaysec.GrpcCommonHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kakaopaysec.GrpcCommonHeader;
  return proto.kakaopaysec.GrpcCommonHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kakaopaysec.GrpcCommonHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kakaopaysec.GrpcCommonHeader}
 */
proto.kakaopaysec.GrpcCommonHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.kakaopaysec.GrpcCommonHeader.ThTrTcd} */ (reader.readEnum());
      msg.setThTrTcd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setThIfTcd(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setThSrcIfTcd(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMgrApvC(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setThTrId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setThScrNo(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setThTrRespTcd(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setThContTrTcd(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setThQryC(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setThDumTrTcd(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setThTrDt(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setThTrDlTmd(value);
      break;
    case 14:
      var value = /** @type {!proto.kakaopaysec.GrpcCommonHeader.ThSysTcd} */ (reader.readEnum());
      msg.setThSysTcd(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setThTrCcd(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setThBizDt(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setThBtnAuthTcd(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setMdaTcd(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setOnlnUserId(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlngDeptCod(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setThPwdErNcIncYn(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setThAcPwdCfmtTcd(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserGrpAuthTcd(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setWrkTmnlId(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setThConnLocTcd(value);
      break;
    case 26:
      var value = /** @type {string} */ (reader.readString());
      msg.setThMacAdr(value);
      break;
    case 27:
      var value = /** @type {string} */ (reader.readString());
      msg.setThIpTcd(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.setThConnPbipAdr(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.setThConnPripAdr(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.addContTrkey(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.setFdsMoblDvcIdfy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kakaopaysec.GrpcCommonHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kakaopaysec.GrpcCommonHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcCommonHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getThTrTcd();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getThIfTcd();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getThSrcIfTcd();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMgrApvC();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getGuid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getThTrId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getThScrNo();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getThTrRespTcd();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getThContTrTcd();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getThQryC();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getThDumTrTcd();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getThTrDt();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getThTrDlTmd();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getThSysTcd();
  if (f !== 0.0) {
    writer.writeEnum(
      14,
      f
    );
  }
  f = message.getThTrCcd();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getThBizDt();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getThBtnAuthTcd();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getMdaTcd();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getOnlnUserId();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getBlngDeptCod();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getThPwdErNcIncYn();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getThAcPwdCfmtTcd();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getUserGrpAuthTcd();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getWrkTmnlId();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getThConnLocTcd();
  if (f.length > 0) {
    writer.writeString(
      25,
      f
    );
  }
  f = message.getThMacAdr();
  if (f.length > 0) {
    writer.writeString(
      26,
      f
    );
  }
  f = message.getThIpTcd();
  if (f.length > 0) {
    writer.writeString(
      27,
      f
    );
  }
  f = message.getThConnPbipAdr();
  if (f.length > 0) {
    writer.writeString(
      28,
      f
    );
  }
  f = message.getThConnPripAdr();
  if (f.length > 0) {
    writer.writeString(
      29,
      f
    );
  }
  f = message.getContTrkeyList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      30,
      f
    );
  }
  f = message.getFdsMoblDvcIdfy();
  if (f.length > 0) {
    writer.writeString(
      31,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.kakaopaysec.GrpcCommonHeader.ThTrTcd = {
  S: 0,
  R: 1
};

/**
 * @enum {number}
 */
proto.kakaopaysec.GrpcCommonHeader.ThSysTcd = {
  D: 0,
  T: 1,
  P: 2,
  L: 3
};

/**
 * optional ThTrTcd th_tr_tcd = 1;
 * @return {!proto.kakaopaysec.GrpcCommonHeader.ThTrTcd}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThTrTcd = function() {
  return /** @type {!proto.kakaopaysec.GrpcCommonHeader.ThTrTcd} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.kakaopaysec.GrpcCommonHeader.ThTrTcd} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThTrTcd = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string th_if_tcd = 2;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThIfTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThIfTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string th_src_if_tcd = 3;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThSrcIfTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThSrcIfTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string mgr_apv_c = 4;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getMgrApvC = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setMgrApvC = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string guid = 5;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string th_tr_id = 6;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThTrId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThTrId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string th_scr_no = 7;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThScrNo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThScrNo = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string th_tr_resp_tcd = 8;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThTrRespTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThTrRespTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string th_cont_tr_tcd = 9;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThContTrTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThContTrTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string th_qry_c = 10;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThQryC = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThQryC = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string th_dum_tr_tcd = 11;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThDumTrTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThDumTrTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string th_tr_dt = 12;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThTrDt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThTrDt = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string th_tr_dl_tmd = 13;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThTrDlTmd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThTrDlTmd = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional ThSysTcd th_sys_tcd = 14;
 * @return {!proto.kakaopaysec.GrpcCommonHeader.ThSysTcd}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThSysTcd = function() {
  return /** @type {!proto.kakaopaysec.GrpcCommonHeader.ThSysTcd} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {!proto.kakaopaysec.GrpcCommonHeader.ThSysTcd} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThSysTcd = function(value) {
  return jspb.Message.setProto3EnumField(this, 14, value);
};


/**
 * optional string th_tr_ccd = 15;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThTrCcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThTrCcd = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string th_biz_dt = 16;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThBizDt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThBizDt = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string th_btn_auth_tcd = 17;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThBtnAuthTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThBtnAuthTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string mda_tcd = 18;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getMdaTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setMdaTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string onln_user_id = 19;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getOnlnUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setOnlnUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string blng_dept_cod = 20;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getBlngDeptCod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setBlngDeptCod = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string th_pwd_er_nc_inc_yn = 21;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThPwdErNcIncYn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThPwdErNcIncYn = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string th_ac_pwd_cfmt_tcd = 22;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThAcPwdCfmtTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThAcPwdCfmtTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string user_grp_auth_tcd = 23;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getUserGrpAuthTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setUserGrpAuthTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional string wrk_tmnl_id = 24;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getWrkTmnlId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setWrkTmnlId = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * optional string th_conn_loc_tcd = 25;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThConnLocTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThConnLocTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 25, value);
};


/**
 * optional string th_mac_adr = 26;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThMacAdr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 26, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThMacAdr = function(value) {
  return jspb.Message.setProto3StringField(this, 26, value);
};


/**
 * optional string th_ip_tcd = 27;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThIpTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 27, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThIpTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 27, value);
};


/**
 * optional string th_conn_pbip_adr = 28;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThConnPbipAdr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 28, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThConnPbipAdr = function(value) {
  return jspb.Message.setProto3StringField(this, 28, value);
};


/**
 * optional string th_conn_prip_adr = 29;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getThConnPripAdr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setThConnPripAdr = function(value) {
  return jspb.Message.setProto3StringField(this, 29, value);
};


/**
 * repeated string cont_trkey = 30;
 * @return {!Array<string>}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getContTrkeyList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 30));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setContTrkeyList = function(value) {
  return jspb.Message.setField(this, 30, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.addContTrkey = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 30, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.clearContTrkeyList = function() {
  return this.setContTrkeyList([]);
};


/**
 * optional string fds_mobl_dvc_idfy = 31;
 * @return {string}
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.getFdsMoblDvcIdfy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 31, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcCommonHeader} returns this
 */
proto.kakaopaysec.GrpcCommonHeader.prototype.setFdsMoblDvcIdfy = function(value) {
  return jspb.Message.setProto3StringField(this, 31, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kakaopaysec.GrpcApproval.prototype.toObject = function(opt_includeInstance) {
  return proto.kakaopaysec.GrpcApproval.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kakaopaysec.GrpcApproval} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcApproval.toObject = function(includeInstance, msg) {
  var f, obj = {
    mgrApvOcurYn: jspb.Message.getFieldWithDefault(msg, 1, ""),
    rsppApvPrcYn: jspb.Message.getFieldWithDefault(msg, 2, ""),
    mgrApvNo: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kakaopaysec.GrpcApproval}
 */
proto.kakaopaysec.GrpcApproval.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kakaopaysec.GrpcApproval;
  return proto.kakaopaysec.GrpcApproval.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kakaopaysec.GrpcApproval} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kakaopaysec.GrpcApproval}
 */
proto.kakaopaysec.GrpcApproval.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMgrApvOcurYn(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRsppApvPrcYn(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMgrApvNo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kakaopaysec.GrpcApproval.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kakaopaysec.GrpcApproval.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kakaopaysec.GrpcApproval} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcApproval.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMgrApvOcurYn();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRsppApvPrcYn();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMgrApvNo();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string mgr_apv_ocur_yn = 1;
 * @return {string}
 */
proto.kakaopaysec.GrpcApproval.prototype.getMgrApvOcurYn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcApproval} returns this
 */
proto.kakaopaysec.GrpcApproval.prototype.setMgrApvOcurYn = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string rspp_apv_prc_yn = 2;
 * @return {string}
 */
proto.kakaopaysec.GrpcApproval.prototype.getRsppApvPrcYn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcApproval} returns this
 */
proto.kakaopaysec.GrpcApproval.prototype.setRsppApvPrcYn = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string mgr_apv_no = 3;
 * @return {string}
 */
proto.kakaopaysec.GrpcApproval.prototype.getMgrApvNo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcApproval} returns this
 */
proto.kakaopaysec.GrpcApproval.prototype.setMgrApvNo = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kakaopaysec.GrpcMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.kakaopaysec.GrpcMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kakaopaysec.GrpcMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    thMsgOputTcd: jspb.Message.getFieldWithDefault(msg, 1, ""),
    msgCod: jspb.Message.getFieldWithDefault(msg, 2, ""),
    msgCn: jspb.Message.getFieldWithDefault(msg, 3, ""),
    thCusrFildNm: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kakaopaysec.GrpcMessage}
 */
proto.kakaopaysec.GrpcMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kakaopaysec.GrpcMessage;
  return proto.kakaopaysec.GrpcMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kakaopaysec.GrpcMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kakaopaysec.GrpcMessage}
 */
proto.kakaopaysec.GrpcMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setThMsgOputTcd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsgCod(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsgCn(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setThCusrFildNm(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kakaopaysec.GrpcMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kakaopaysec.GrpcMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kakaopaysec.GrpcMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getThMsgOputTcd();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMsgCod();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMsgCn();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getThCusrFildNm();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string th_msg_oput_tcd = 1;
 * @return {string}
 */
proto.kakaopaysec.GrpcMessage.prototype.getThMsgOputTcd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcMessage} returns this
 */
proto.kakaopaysec.GrpcMessage.prototype.setThMsgOputTcd = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string msg_cod = 2;
 * @return {string}
 */
proto.kakaopaysec.GrpcMessage.prototype.getMsgCod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcMessage} returns this
 */
proto.kakaopaysec.GrpcMessage.prototype.setMsgCod = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string msg_cn = 3;
 * @return {string}
 */
proto.kakaopaysec.GrpcMessage.prototype.getMsgCn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcMessage} returns this
 */
proto.kakaopaysec.GrpcMessage.prototype.setMsgCn = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string th_cusr_fild_nm = 4;
 * @return {string}
 */
proto.kakaopaysec.GrpcMessage.prototype.getThCusrFildNm = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcMessage} returns this
 */
proto.kakaopaysec.GrpcMessage.prototype.setThCusrFildNm = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kakaopaysec.GrpcFep.prototype.toObject = function(opt_includeInstance) {
  return proto.kakaopaysec.GrpcFep.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kakaopaysec.GrpcFep} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcFep.toObject = function(includeInstance, msg) {
  var f, obj = {
    fepChanId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fepIfId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fepIfProcId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    fepTrNodeNo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fepRespTrId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    fepTrTmerKeyVal: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kakaopaysec.GrpcFep}
 */
proto.kakaopaysec.GrpcFep.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kakaopaysec.GrpcFep;
  return proto.kakaopaysec.GrpcFep.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kakaopaysec.GrpcFep} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kakaopaysec.GrpcFep}
 */
proto.kakaopaysec.GrpcFep.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFepChanId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFepIfId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFepIfProcId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFepTrNodeNo(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFepRespTrId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFepTrTmerKeyVal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kakaopaysec.GrpcFep.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kakaopaysec.GrpcFep.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kakaopaysec.GrpcFep} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kakaopaysec.GrpcFep.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFepChanId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFepIfId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFepIfProcId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFepTrNodeNo();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFepRespTrId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFepTrTmerKeyVal();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string fep_chan_id = 1;
 * @return {string}
 */
proto.kakaopaysec.GrpcFep.prototype.getFepChanId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcFep} returns this
 */
proto.kakaopaysec.GrpcFep.prototype.setFepChanId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string fep_if_id = 2;
 * @return {string}
 */
proto.kakaopaysec.GrpcFep.prototype.getFepIfId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcFep} returns this
 */
proto.kakaopaysec.GrpcFep.prototype.setFepIfId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string fep_if_proc_id = 3;
 * @return {string}
 */
proto.kakaopaysec.GrpcFep.prototype.getFepIfProcId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcFep} returns this
 */
proto.kakaopaysec.GrpcFep.prototype.setFepIfProcId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string fep_tr_node_no = 4;
 * @return {string}
 */
proto.kakaopaysec.GrpcFep.prototype.getFepTrNodeNo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcFep} returns this
 */
proto.kakaopaysec.GrpcFep.prototype.setFepTrNodeNo = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string fep_resp_tr_id = 5;
 * @return {string}
 */
proto.kakaopaysec.GrpcFep.prototype.getFepRespTrId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcFep} returns this
 */
proto.kakaopaysec.GrpcFep.prototype.setFepRespTrId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string fep_tr_tmer_key_val = 6;
 * @return {string}
 */
proto.kakaopaysec.GrpcFep.prototype.getFepTrTmerKeyVal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.kakaopaysec.GrpcFep} returns this
 */
proto.kakaopaysec.GrpcFep.prototype.setFepTrTmerKeyVal = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.kakaopaysec);
